spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 1024Mi
          env:
          - name: ACTIVEMQ_SERVICE_NAME
            value: broker-amq-tcp
#          - name: ACTIVEMQ_BROKER_USERNAME
#            value: admin
#          - name: ACTIVEMQ_BROKER_PASSWORD
#            value: admin
